### ISSUE TITLE
MythicMetalDecorations crashes on 1.18.2

### ISSUE THREAD

**Issue by aninusmuffin** [Noaaan/MythicMetalsDecorations#11]
https://mclo.gs/5pkubxL#L218

MythicMetalDecorations 0.2.2

**Comment by StockiesLad** [comment]
same issue here

**Comment by Noaaan** [comment]
I apologize for the late response.
Looking more into this issue its due to an internal class from Mythic Metals being changed. I no longer support MM Decorations for 1.18.x versions. 
If you still wish to use MM Decorations for 1.18, then please try downgrading to 0.14.4 and see if it lets you launch.
